### ISSUE TITLE
ERROR: Service 'logspout' failed to build: lstat build.sh: no such file or directory

### ISSUE THREAD

**Issue by baksosapi** [garystafford/spring-music-docker#1]
ian-mbp:spring-music-docker wildan$ docker-compose up -d
Building elk
Step 1 : FROM willdurand/elk
 ---> 26bad05fb77c
Step 2 : MAINTAINER Gary A. Stafford garystafford@rochester.rr.com
 ---> Using cache
 ---> b63c8c8598c4
Step 3 : ENV REFRESHED_AT 2015-09-02
 ---> Using cache
 ---> 84d620542ed4
Step 4 : COPY logstash-logspout.conf /etc/logstash/logstash-logspout.conf
 ---> Using cache
 ---> 8245a234070e
Successfully built 8245a234070e
WARNING: Image for service elk was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building nosqldb
Step 1 : FROM mongo:latest
 ---> 7f09d45df511
Step 2 : MAINTAINER Gary A. Stafford garystafford@rochester.rr.com
 ---> Using cache
 ---> 56ee5e6beb43
Step 3 : ENV REFRESHED_AT 2015-09-02
 ---> Using cache
 ---> 8cb4f60f1d21
Step 4 : VOLUME /data/db
 ---> Using cache
 ---> 7a94a32b1443
Step 5 : WORKDIR /data
 ---> Using cache
 ---> 31302046f430
Step 6 : CMD mongod --smallfiles
 ---> Using cache
 ---> 3de8c61a2974
Successfully built 3de8c61a2974
WARNING: Image for service nosqldb was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building app01
Step 1 : FROM tomcat:latest
 ---> 25e98610c7d0
Step 2 : MAINTAINER Gary A. Stafford garystafford@rochester.rr.com
 ---> Using cache
 ---> 865c54b1cd17
Step 3 : ENV REFRESHED_AT 2015-09-20
 ---> Using cache
 ---> f792aed28fc9
Step 4 : ENV GITHUB_REPO https://github.com/garystafford/spring-music/raw/build-artifacts
 ---> Using cache
 ---> 8f0969a386e3
Step 5 : ENV APP_FILE spring-music.war
 ---> Using cache
 ---> 16daf82ef284
Step 6 : RUN apt-get update -y &&   apt-get install wget -y &&   wget -O /usr/local/tomcat/webapps/ROOT.war ${GITHUB_REPO}/${APP_FILE} &&   mv /usr/local/tomcat/webapps/ROOT /usr/local/tomcat/webapps/_ROOT
 ---> Using cache
 ---> 02c93eb4fb93
Step 7 : COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
 ---> Using cache
 ---> 272fc4fc870f
Successfully built 272fc4fc870f
WARNING: Image for service app01 was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building app02
Step 1 : FROM tomcat:latest
 ---> 25e98610c7d0
Step 2 : MAINTAINER Gary A. Stafford garystafford@rochester.rr.com
 ---> Using cache
 ---> 865c54b1cd17
Step 3 : ENV REFRESHED_AT 2015-09-20
 ---> Using cache
 ---> f792aed28fc9
Step 4 : ENV GITHUB_REPO https://github.com/garystafford/spring-music/raw/build-artifacts
 ---> Using cache
 ---> 8f0969a386e3
Step 5 : ENV APP_FILE spring-music.war
 ---> Using cache
 ---> 16daf82ef284
Step 6 : RUN apt-get update -y &&   apt-get install wget -y &&   wget -O /usr/local/tomcat/webapps/ROOT.war ${GITHUB_REPO}/${APP_FILE} &&   mv /usr/local/tomcat/webapps/ROOT /usr/local/tomcat/webapps/_ROOT
 ---> Using cache
 ---> 02c93eb4fb93
Step 7 : COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
 ---> Using cache
 ---> 272fc4fc870f
Successfully built 272fc4fc870f
WARNING: Image for service app02 was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building logspout
Step 1 : FROM gliderlabs/logspout:master
# Executing 3 build triggers...

Step 1 : COPY ./build.sh /src/build.sh
ERROR: Service 'logspout' failed to build: lstat build.sh: no such file or directory

**Comment by garystafford** [comment]
Thank you for pointing out this issue. It is not an issue with this project, but with the dependent gliderlabs' custom logspout image. See the open issue here: [https://github.com/gliderlabs/logspout/issues/212](https://github.com/gliderlabs/logspout/issues/212). I suggest subscribing to that issue, so you keep up to date with a fix.
